pysmt/pysmt

patches/pycudd.README, patches/pycudd.patch, pysmt/factory.py, pysmt/solvers/bdd.py, pysmt/solvers/eager.py, pysmt/test/examples.py, pysmt/test/test_bdd.py, pysmt/test/test_env.py, pysmt/test/test_lira.py, pysmt/test/test_models.py, pysmt/test/test_regressions.py, pysmt/test/test_solving.py
- Added files in patches/ to explain how to install PyCUDD 
- This also introduces a few fixes to pycudd and the method pycudd.GetDefaultManager()
- Implemented BddSolver as an incremental solver
- Added 'bdd' solver in Factory
- Most tests assumed that all solvers could work on QF_UFLIRA. Explicited added the requirement.
- Added ad-hoc tests
=> Integrated PyCUDD as BDD Solver.

pysmt/test/test_bdd.py, pysmt/test/test_rand.py
Made the tests conditional to the presence of the solver
=> BUGFIX: Some tests required pycudd, z3 and msat.

docs/CHANGES.rst, pysmt/formula.py, pysmt/shortcuts.py, pysmt/test/test_formula.py
* Added support for Min and Max shortcuts
* Refined AtMostOne and ExactlyOne shortcuts to support polymorphic arguments
=> Added support for Min and Max shortcuts

install.py, pysmt/solvers/cvc4.py, pysmt/solvers/msat.py, pysmt/solvers/yices.py, pysmt/solvers/z3.py, pysmt/test/test_regressions.py
* Cleaned up solver encoders, removing useless assertions.
* This also solves issue #7
=> Cleaned up solver encoders, removing useless assertions.

pysmt/cmd/install.py, shippable.yml
Compilation of CVC4 specifies a target directory for the binaries
=> CVC4 Prefix

pysmt/cmd/install.py, shippable.yml
Tis should fix the SMT2 wrappers
=> Moved CI to the new version of MathSAT

docs/CHANGES.rst, pysmt/exceptions.py, pysmt/factory.py, pysmt/shortcuts.py, pysmt/smtlib/solver.py, pysmt/solvers/bdd.py, pysmt/solvers/cvc4.py, pysmt/solvers/msat.py, pysmt/solvers/pico.py, pysmt/solvers/solver.py, pysmt/solvers/yices.py, pysmt/solvers/z3.py, pysmt/test/__init__.py, pysmt/test/test_unsat_cores.py
This PR introduces support for UNSAT cores in msat and z3
=> Unsat cores support

docs/CHANGES.rst, pysmt/factory.py, pysmt/logics.py, pysmt/shortcuts.py, pysmt/solvers/msat.py, pysmt/solvers/z3.py, pysmt/test/__init__.py, pysmt/test/test_env.py, pysmt/test/test_qe.py
In this PR we introduce a logic-based selection of the quantifier eliminators, analogously to the Solver case. In addition the factory code has been re-factored.
This addresses issues #16 and #71.
=> Quantifiler Elimination selector

pysmt/solvers/pico.py
=> Added support for picosat assumptions

pysmt/environment.py, pysmt/fnode.py, pysmt/oracles.py, pysmt/shortcuts.py, pysmt/test/test_size.py
Addressing #34 with dedicated oracle supporting four measures (for now) of the size of a formula.
=> Fnode size

docs/CHANGES.rst, pysmt/cmd/install.py, pysmt/factory.py, pysmt/solvers/bdd.py, pysmt/test/test_bdd.py, pysmt/test/test_env.py
The BDD-based quantifier elimination for BOOL was already implemented, but a proper QE interface was missing. This PR adds BDD-based QE as a proper pysmt quantifier eliminator.
=> QE: Added BDD-based interface for quantifier elimination

pysmt/solvers/bdd.py
Removed recursive non-memoized back-conversion in BDD solver and implemented a purely-iterative, memoized version.
=> BDD: iterative back-conversion 

pysmt/solvers/z3.py, pysmt/test/test_regressions.py
The problem was caused by a missing conversion from decl to term
=> BUGFIX: Fixed an assertion error arising when iterating over a Z3Model

shippable.yml
* Remmoved the use of multiprocessing that is problematic and does not yield any speedup
* Removed Python 3.3 that is almost useless, having Pythn 3.4 testing.
=> SHIPPABLE: Updated CI configuration.

pysmt/factory.py, pysmt/shortcuts.py, pysmt/solvers/interpolation.py, pysmt/solvers/msat.py, pysmt/solvers/z3.py, pysmt/test/test_interpolation.py
This is just a clean branch for PR #103.
All the credits go to @agriggio
=> Interpolation Support

pysmt/solvers/bdd.py, pysmt/test/test_bdd.py
Added support for dynamic reordering and specification of an initial ordering for BddSolver.
This addresses #89
=> BDD: Added static ordering support and dynamic reordering for BDDs

shippable.sh, shippable.yml
Now the tests comprehend a new setting in which all the solvers are
contemporary enabled and covergae analysis is enabled.
=> CI: Enabled coverage test with all the solvers in shippable

pysmt/simplifier.py, pysmt/test/test_walkers.py, pysmt/walkers/identitydag.py
- Extends test_walkers to run all examples over the IdentityDagWalker.
- Simplified IdentitiDagWalker using *args
=> Fixed #112: Added support for BV in IdentityDagWalker

pysmt/solvers/msat.py, pysmt/test/examples.py, pysmt/test/test_qe.py, pysmt/walkers/dag.py, pysmt/walkers/identitydag.py
- Improved testing of QE, by running QE on all examples formula.
- This also cleans-up the dag walker, removing dead-code
=> BUGFIX: Fixed bug in MSatQuantifierElimination with quantifier alternation

README.rst
Added tables in README.rst explaining the current status os the features supported by each solver: this partially addresses #115
=> Update README to better explain which features are supported.

README.rst, docs/CHANGES.rst, pysmt/cmd/install.py, pysmt/solvers/bdd.py, pysmt/test/test_bdd.py, shippable.yml
Ported pysmt BDD solving features to use repycudd version of pycudd, thus having a re-entrant version of the library
=> Ported pysmt from pycudd to repycudd

pysmt/decorators.py, pysmt/exceptions.py, pysmt/operators.py, pysmt/solvers/bdd.py, pysmt/solvers/cvc4.py, pysmt/solvers/msat.py, pysmt/solvers/pico.py, pysmt/solvers/yices.py, pysmt/solvers/z3.py, pysmt/test/test_dwf.py, pysmt/test/test_solving.py, pysmt/test/test_walkers.py, pysmt/walkers/generic.py
- Added decorator @catch_conversion_error, to be used in the converters, to detect an UnsupportedOperaratorError and transform it in a nicer error message.
- Added simple test that checks the raising of this exception
=> Fixed Issue #128

pysmt/fnode.py, pysmt/typing.py
- Documentation for all FNode methods.
- Remove calls to shortcuts from FNode.
=> Fixed #116: Implemented FNode.get_type.

pysmt/operators.py, pysmt/oracles.py, pysmt/rewritings.py, pysmt/simplifier.py, pysmt/smtlib/printers.py, pysmt/solvers/msat.py, pysmt/substituter.py, pysmt/test/test_oracles.py, pysmt/test/test_solving.py, pysmt/test/test_walkers.py, pysmt/type_checker.py, pysmt/walkers/generic.py
=> Walkers: added method to set the walking function 

pysmt/rewritings.py, pysmt/walkers/dag.py
@mikand , I just realized we did not merge this. Was there a reason, or did we simply forget?
I'd be in for merging it. I think the extension that we did of the DagWalker is clean and could be useful in other contexts.
=> Rewriting of NNFizer as DagWalker

pysmt/solvers/z3.py
Converted Z3 back conversion from recursive to iterative
=> Z3: iterative back conversion

pysmt/smtlib/parser.py, pysmt/test/smtlib/parser_utils.py, pysmt/test/smtlib/small_set/QF_LIA/issue_159.smt2
Suggested fix has been implemented and regression test has been added.
=> Fixed issue #159

docs/CHANGES.rst, pysmt/rewritings.py, pysmt/test/test_rewritings.py
A formula is rewritten as an And Inverted Graph. This takes into account only the boolean part of the formula, while the thoery parts remains unchanged.
=> AIG Rewriting

pysmt/rewritings.py, pysmt/test/test_regressions.py
It was behaving exactly like cnf(), hence returning a formula instead of a set.
A regression test has been added.
=> BUGFIX: Fixed bug in cnf_as_set() function

pysmt/formula.py, pysmt/smtlib/parser.py, pysmt/smtlib/printers.py, pysmt/smtlib/script.py, pysmt/smtlib/solver.py, pysmt/test/examples.py, pysmt/test/smtlib/test_generic_wrapper.py, pysmt/test/smtlib/test_parser_extensibility.py, pysmt/test/test_bv.py, pysmt/test/test_regressions.py, pysmt/type_checker.py, pysmt/typing.py, pysmt/utils.py
- Refactoring of the parser to allow extensibility
- a few minor hacks to gain performance (~2 seconds executing all the tests in tests/smtlib)
=> PARSER: Extensibility

README.rst, examples/README.rst, examples/allsmt.py, pysmt/formula.py, pysmt/shortcuts.py, pysmt/test/test_formula.py
Added simple example of all-smt. This also shows how to call the logic oracle, to detect the logic of a formula.
=> Example for All SMT

pysmt/cmd/install.py
Exported install.py changes for btor from #171
=> Updated install.py for Boolector

pysmt/printers.py, pysmt/test/test_printing.py
- Test for checking output of HRPrinter
- New version of the HRPrinter uses aux functions for printing of
binary and n-ary operators. A few operators still use ad-hoc methods.
The aux functions are called from walk_* to make it easier to change
the behavior of the printer.
=> Simplified HRPrinter

examples/README.rst, examples/parallel.py, examples/sudoku/README.rst, pysmt/test/examples.py
Simple example for using ```multiprocessing.Pool.map``` and ```multiprocessing.Pool.apply_async``` in pySMT.
=> Examples: Multi-processing with pySMT

README.rst
- Change order of the section
- Added Architectural Diagram
- Added badges for multiple services
=> Revised README.rst

docs/CHANGES.rst, pysmt/factory.py, pysmt/solvers/qelim.py, pysmt/test/examples.py, pysmt/test/test_bdd.py, pysmt/test/test_printing.py, pysmt/test/test_shannon_expansion.py, pysmt/utils.py
Implemented the classical shannon expansion method as a quantifier eliminator for the BOOL logic. This addresses #183.
=> Implemented Shannon-Expansion

pysmt/smtlib/parser.py, pysmt/smtlib/script.py, pysmt/test/test_regressions.py
Fixed issue #204 by adding a proper quoting when serializing a set-info SMTLib command
=> Fixed issue #204 

pysmt/rewritings.py, pysmt/test/test_cnf.py
Fixed bug in CNF conversion of implication
The relative no-regression test has been added
=> BUGFIX in CNF converter

.travis.yml, pysmt/cmd/installers/cvc4.py
This solves the caching problem in Travis
=> Fixed CVC4 Installer to use binding dir for CVC4_bin

pysmt/cmd/install.py, pysmt/cmd/installers/base.py, pysmt/solvers/yices.py
=> Ported to Yices 2.4.1

pysmt/fnode.py, pysmt/test/test_formula.py
BV: Support for BV Infix notation
Tests explain quirks related to mixing python constants and pySMT
constants.
Moreover, infix operators are reserved to unsigned operations. Signed
operators (and operators that cannot easily be mapped into python
operators) need to rely on the l.Operator(r) syntax.
Apart from this, the rest of the infix notation is straight-forward
=> BV Infix notation

pysmt/formula.py, pysmt/test/test_formula.py, pysmt/test/test_regressions.py
Fixes #242.
Thanks to Martin (@hastyboomalert) for reporting it.
=> BUGFIX: Fixed bug in ExactlyOne args unpacking

.travis.yml, pysmt/cmd/install.py, pysmt/cmd/installers/bdd.py
This enables support for 3.4 and 3.5
=> Upgrade rePyCUDD to 75fe055

pysmt/type_checker.py
This also makes the code below more pythonic
=> Removed dependency from six in type_checker.

pysmt/logics.py, pysmt/simplifier.py, pysmt/solvers/bdd.py, pysmt/test/test_logics.py, pysmt/test/test_simplify.py, pysmt/walkers/dag.py
Simplifier based on BDD conversion. Provides additional utilities like validation and handling of SMT formulas via boolean abstraction.
=> Bdd simplify

SMT-LIB/parse_and_print.py, pysmt/printers.py, pysmt/smtlib/parser.py, pysmt/smtlib/printers.py, pysmt/test/test_dwf.py, pysmt/test/test_printing.py, pysmt/walkers/tree.py
The algorithm works by keeping an explicit stack of walking functions ***that are now required to be generators***
All the wlakers within PySMT have been modified accordingly
=> Non-Recursive TreeWalker

pysmt/fnode.py, pysmt/formula.py, pysmt/test/test_array.py, pysmt/test/test_bv.py, pysmt/test/test_formula.py, pysmt/test/test_regressions.py
This increases the coverage of tests for FNode.
**Note**: This also changes the implementation of FNode.array_value_get, since the current implementation was incorrect.
=> Tests for FNode

pysmt/exceptions.py
This is useful for catching expected run-time errors
=> add a base class SmtException for all custom exceptions raised by pySMT

pysmt/shortcuts.py
=> Extend docstrings (shortcuts.py)

pysmt/smtlib/script.py, pysmt/test/smtlib/test_smtlibscript.py
This is useful for generating scripts for solvers that only work for specific logics.
=> Allow the user to specify a custom logic for smtlibscript_from_formula()

README.rst
=>  Link to Google Group in Readme.md

pysmt/__init__.py
Fixed issue #389 by adding a missing catch condition
=> Fixed issue #389

pysmt/solvers/btor.py, pysmt/test/test_regressions.py
Porting PR #394 in master by adding no-regression tests.
Thanks to @alexeyignatiev for the contribution
=> Boolector Assumptions Fix

examples/README.rst, examples/xor.py
A simple example of equivalence checking using BitVectors.
=> Examples: Equivalence checking of XOR rewriting

pysmt/smtlib/parser.py, pysmt/test/test_regressions.py
Thanks to @ahmedirfan1983 for reporting this.
=> SMTLIB: Fixed bug in declare-const parsing

pysmt/cmd/install.py, pysmt/cmd/installers/cvc4.py, pysmt/solvers/cvc4.py
Note: CVC4 does not distinguish anymore between IFF and EQUALS.
See https://github.com/CVC4/CVC4/commit/1f4b954a2cc7667a56a3007fa75c125fba93ed23
=> CVC4: Upgrade to 1.5

pysmt/fnode.py, pysmt/test/test_array.py
Introduce textual infix notation for Store and Select
=> Arrays: Infix notation for Store and Select

pysmt/fnode.py, pysmt/test/test_euf.py
=> Added support for EUF infix notation

examples/README.rst, examples/theory_combination.py
Simple example using BV, Int, Real and Array.
=> Examples: Theory Combination

pysmt/cmd/installers/msat.py
Force rpath rewriting in MathSAT installer.
=> MathSAT: Fixed installer for OSX

.travis.yml, ci/travis_after_success.sh, ci/travis_before_install.sh, ci/travis_install.sh, ci/travis_script.sh, pysmt/cmd/install.py, pysmt/cmd/installers/base.py, pysmt/cmd/installers/yices.py
This PR uses a new feature of Travis that allows the mixture of linux and osx builds. For now, on osx we test MathSAT and Z3 only, in the future we can add the other solvers.
Note: I configured the CI so that osx builds are run ony on PRs and on master
=> CI with osx

.travis.yml, ci/travis_after_success.sh, ci/travis_before_install.sh, ci/travis_install.sh, ci/travis_script.sh, pysmt/cmd/install.py, pysmt/cmd/installers/base.py, pysmt/cmd/installers/yices.py, pysmt/shortcuts.py, pysmt/smtlib/parser/parser.py, pysmt/smtlib/script.py, pysmt/test/smtlib/test_smtlibscript.py, pysmt/test/test_regressions.py
fixes #499.
This is fixed by adding a case in the `evaluate_command` function.
A test was added to check both 0-ary and 1-ary sorts.
=> Fix declare-sort bug

.travis.yml, ci/check_python_version.py, ci/travis_before_install.sh, ci/travis_install.sh, ci/travis_script.sh
As part of the deprecation of python 2.7, this changes the version of pypy we are testing against to pypy3.5.
=> CI: Upgrade pypy2.7 to pypy3.5

pysmt/solvers/msat.py, pysmt/test/test_solving.py
This modification adds support to set the preferred variables polarity when using MathSAT solver
=> MathSAT: Preferred variables with polarity

pysmt/smtlib/parser/parser.py
Removed print lines from the smtlib parser code.
=> removed prints from smt parser

examples/README.rst, examples/strings.py
Example on how to use the Theory of Strings.
=> Examples: Strings

pysmt/typing.py
=> Remove unused String type

pysmt/simplifier.py, pysmt/test/examples.py
=> Fix #563: Simplifier StrIndexOf capitalization

pysmt/cmd/install.py, pysmt/cmd/installers/btor.py
* Upgrade boolector to f689f
* Pass parameters to configure.sh through env variables (see discussion on boolector #24)
=> BTOR: Upgrade to f689f

make_distrib.sh
Follow-up of #575 
This PR aims at increasing the version number before appending the `.devX` part to have a correct version numbering in PyPI
=> Dev Version Numbering

pysmt/smtlib/printers.py, pysmt/test/test_regressions.py
Fixed printing as suggested by @ekiwi in #584
=> Fixed Issue #584

pysmt/solvers/btor.py, pysmt/solvers/msat.py, pysmt/solvers/solver.py
This pull requests adds support for getting unsat cores from boolector. Named unsat cores are not supported here yet.
=> Unsat cores from boolector

pysmt/solvers/msat.py
Thanks to @smover for signaling the issue and proposing the fix.
=> Fixed issue #617

pysmt/smtlib/solver.py, pysmt/test/smtlib/test_generic_wrapper.py
The `SmtLibSolver` class was not dealing correctly with the `pending_pop` mechanism.
And the `SmtLibOptions` class was mishandling the `debug_interaction` option.
Thanks to @smover for signaling the issues.
=> Fixed issue #616 and #615

pysmt/oracles.py, pysmt/test/test_regressions.py
Added proper support for boolean-typed array in the `AtomsOracle`
Fixes #643
=> Add support for boolean-typed array in the AtomsOracle

azure-pipelines.yml, ci/install_unix.sh, pysmt/cmd/installers/cvc4.py, pysmt/cmd/installers/yices.py, pysmt/solvers/z3.py
Azure CI is broken due to updates on azure itself an on some solver repos. This PR will restore the CI functionality.
=> Fixing Azure CI

ci/install_unix.sh, ci/run_unix.sh, ci/run_win.sh, dev-requirements.txt, docs/development.rst, health_check.sh, pysmt/solvers/z3.py, pysmt/test/smtlib/parser_utils.py, pysmt/test/smtlib/test_fuzzed.py, pysmt/test/smtlib/test_parser_lra.py, pysmt/test/smtlib/test_parser_qf_arrays.py, pysmt/test/smtlib/test_parser_qf_lia.py, pysmt/test/smtlib/test_parser_qf_lira.py, pysmt/test/smtlib/test_parser_qf_lra.py, pysmt/test/smtlib/test_parser_qf_nia.py, pysmt/test/smtlib/test_parser_qf_nra.py, pysmt/test/smtlib/test_parser_qf_ufbv.py, pysmt/test/test_cnf.py, pysmt/test/test_simplify.py, pytest.ini, run_all_tests.sh, run_tests.sh
=> Switched from nosetests to pytest

pysmt/solvers/yices.py, pysmt/test/test_regressions.py
Thanks to @EnricoMagnago for signaling this issue
=> Fixed a bug in yices quantifier support and added regression test

CONTRIBUTORS
@johnyf Could you comment on this PR as understanding that you agree with our [CLA](https://pysmt.readthedocs.io/en/latest/development.html#licensing) .
We recently changed how we enforce this, and your PR https://github.com/pysmt/pysmt/pull/659 slipped through the change.
Thanks again for contributing!
=> Add missing contributor

pysmt/solvers/solver.py
This issue has been signaled by @EnricoMagnago
=> Fixed reset_assertion method for incremental-tracking solvers

CONTRIBUTORS, pysmt/formula.py, pysmt/smtlib/parser/__init__.py, pysmt/test/smtlib/test_smtlibscript.py
a) Updated "UF_LIRA" to "UFLIRA"  to correct the test_smtlibscript.py
b) Updated minor change to correct two DeprecationWarnings.
=> Minor Corrections

pysmt/cmd/installers/bdd.py
=> Added fallback to Swig3 to address as much as possible issue #682

pysmt/solvers/msat.py, pysmt/test/test_unsat_cores.py
=> Fix iss694

pysmt/cmd/installers/cvc4.py
=> Fixed CVC4 installer after upstream repository renaming

pysmt/smtlib/parser/parser.py
Do not use `FNode.substitute` in SmtLibExecutionCache: the method relies on the substituter in the environment obtained via `get_env`, this might not match the environment given to the SmtLibParser and cause errors.
I also applied the following minor changes.
Remove `\` within parentheses.
Remove duplicated call to `Dict.get`.
=> Remove call to `FNode.substitute` in SmtLibExecutionCache

.mailmap, CONTRIBUTORS, pysmt/smtlib/printers.py, pysmt/smtlib/script.py, pysmt/test/test_printing.py
Added support of SMT-LIB annotations printing
=> Added printing of annotations to smt lib printers

pysmt/solvers/z3.py
Following discoveries in #465, this PR offers a workaround that should definitely fix the tests
=> Workaround to fix Z3 segfault

.mailmap, CONTRIBUTORS
Adding Arrighi, Contaldo and Trentin as contributors
=> adding Arrighi, Contaldo and Trentin as contributors

pysmt/formula.py
=> Grammar correction

CONTRIBUTORS, examples/parallel.py
=> example/parallel.py: typo fix

pysmt/cmd/installers/base.py, pysmt/cmd/installers/bdd.py, pysmt/cmd/installers/btor.py, pysmt/cmd/installers/cvc4.py
* Fix for https://github.com/pysmt/pysmt/issues/764
Mostly followed the migration advice from https://peps.python.org/pep-0632/#migration-advice
=> Remove deprecated distutils

CONTRIBUTORS, pysmt/smtlib/parser/__init__.py
=> Fixed removed imp module in Python 3.12

ci/install_unix.sh, pysmt/cmd/install.py, pysmt/cmd/installers/msat.py
=> Fix CI on Master

pysmt/cmd/installers/btor.py, pysmt/solvers/btor.py
Btor CI is broken due to an upstream update in the ubuntu image, this PR aims at fixing the issue.
=> Fix btor CI

pysmt/rewritings.py, pysmt/test/test_cnf.py, pysmt/test/test_regressions.py
=> Fix issue 802 on CNFizer

pysmt/smtlib/parser/parser.py, pysmt/test/smtlib/test_annotations.py
=> Parse value annotations with ":" as keywords
