- pysmt/environment.py
- pysmt/operators.py
- pysmt/test/test_dwf.py
- pysmt/walkers/generic.py
Whenever a walker finds an unexpected node-type, it will ask the environment which function to use. This can be used to define new node-types. See test_dwf.py for an example usage.
> Dynamic Walker Function

- pysmt/logics.py
- pysmt/test/__init__.py
- pysmt/test/smtlib/parser_utils.py
- pysmt/test/smtlib/test_parser_lra.py
- pysmt/test/smtlib/test_parser_qf_lia.py
- pysmt/test/smtlib/test_parser_qf_lira.py
- pysmt/test/smtlib/test_parser_qf_lra.py
- pysmt/test/test_euf.py
- pysmt/test/test_formula.py
- pysmt/test/test_int.py
- pysmt/test/test_logics.py
- pysmt/test/test_models.py
- pysmt/test/test_msat_back.py
- pysmt/test/test_regressions.py
- pysmt/test/test_solving.py
Added _skipIfNoSolverForLogic_ decorator. This should be used instead of the deprecated _skipIfNoSolverAvailable_. The goal is to be specific about the test requirement. This makes it possible to run pySMT with only a subset of the solvers. Implicitly, we were assuming that a solver for UFLIRA was always available for most of those tests.
>  Improved test handling when solvers are not available

- pysmt/solvers/cvc4.py
- pysmt/test/smtlib/test_parser_lra.py
- pysmt/test/smtlib/test_parser_qf_lia.py
- pysmt/test/smtlib/test_parser_qf_lira.py
- pysmt/test/smtlib/test_parser_qf_lra.py
- pysmt/test/test_solving.py
* Generator tests were not executed correctly due to the new skip decorator
* CVC4 was failing some tests due to "unknown" reply
For the time being, CVC4 has been limited to the quantifier-free logic
fragments.
> Fixed problems in tests due to skip decorators

- install.py
- shippable.sh
- shippable.yml
We now test pysmt over each solver independently (and without solvers). 
For now, we limit the tests to python 2.7 - We can think to extend this in the future.
*Note*: Bdd tests fail randomly.
> Continuous Integration for each solver

- pysmt/environment.py
- pysmt/logics.py
- pysmt/oracles.py
- pysmt/smtlib/parser.py
- pysmt/test/examples.py
- pysmt/test/test_logics.py
- pysmt/test/test_oracles.py
- pysmt/test/test_typechecker.py
- pysmt/type_checker.py
*TO BE DISCUSSED*
This breaks the logic class into two pieces. Logic and Theory. Theory contains the information about the theories in use, logic contains info on quantificiation, name and description.
This division makes sense when working with the logic oracle, since detecting the theory in use requires handling all the intermediate logics. 
This introduces also the shortcut _get_logic()_ that returns the closest logic for a formula. This is done using and oracle, and could probably be improved.
> get_logic + Logic Refactoring

- pysmt/smtlib/parser.py
- pysmt/solvers/bdd.py
- pysmt/solvers/cvc4.py
- pysmt/solvers/msat.py
- pysmt/solvers/solver.py
- pysmt/solvers/yices.py
- pysmt/solvers/z3.py
- pysmt/test/test_regressions.py
Fixed and uniformed exit() method of solvers: a common _destroyed flag
has been introduced to avoid multiple calls to the cleanup code of
each solver that caused segmentation faults with yices
> BUGFIX for the exit() method

- pysmt/solvers/eager.py
- pysmt/test/test_models.py
Model iterator uses all symbols defined in the formula manager. Many of those symbols are not defined in the EagerModel assignment. Therefore, we modify the iterator of EagerModel to consider only the defined symbols. If the model needs to consider all variables, one should call the _comple_model()_ method.
> EagerModel iterator

- pysmt/solvers/eager.py
- pysmt/test/test_eager_model.py
Statements such as
```
if x in model:
...
```
were yielding an incorrect result (default to False).  This could cause bugs in situations in which we are not sure on whether we are using a dictionary or an EagerModel, since the two behaviors were different.
> Bugfix: Implemented EagerModel.__contains__

- pysmt/solvers/bdd.py
- pysmt/solvers/cvc4.py
- pysmt/solvers/msat.py
- pysmt/solvers/solver.py
- pysmt/solvers/yices.py
- pysmt/solvers/z3.py
A Converter Interface provides only two methods .convert() and .back()
A Solver needs to provide a converter property.
> Issure #23: Added interface for Converter and enforced property Solver.converter

- MANIFEST.in
- README.rst
- setup.py
- shell.py
We create 3 "binaries" after installation:
* pysmt : full shell that defaults to smtlib behavior
* pysmt-shell: shell that defaults to interactive
* pystm-install: alias for install.py
This addresses #10
> Creates "binaries" during installation

- install.py
- shippable.sh
- shippable.yml
This is meant to avoid re-compiling the solvers each time during CI.
The env variable PYSMT_BIN_MIRROR can be set to define the location of
the binary mirror. Note that this is not implemented for all solvers.
Finally, CVC4 required some slightly different handling, thus the
pythonpath in shippable.yml has been changed.
> Binary mirrors for solvers: CUDD, CVC4 and Z3.

- docs/CHANGES.rst
- pysmt/factory.py
- pysmt/logics.py
- pysmt/oracles.py
- pysmt/shortcuts.py
- pysmt/test/test_solving.py
This PR introduces the following changes:
- The special logic pysmt.logics.AUTO is introduced. This logic can be used in the shortcuts (is_sat, etc) when we are not sure of the formula that we are solving. This will select the smallest logic needed.
-  Factory.default_logic (by default QF_UFLIRA) used whenever a logic has not been specified
- Deprecation of _quantified_ argument from all shortcuts. This argument remains in the Factory.Solver, with the semantics that it requires the quantified version of the default logic.
__THIS MIGHT BREAK EXISTING TOOLS RELYING ON THE (DEPRECATED) quantified OPTION__
> Using get_logic oracle in shortcuts and defining default for Factory

- docs/CHANGES.rst
- pysmt/environment.py
- pysmt/fnode.py
- pysmt/oracles.py
- pysmt/shortcuts.py
- pysmt/simplifier.py
- pysmt/smtlib/printers.py
- pysmt/smtlib/script.py
- pysmt/smtlib/solver.py
- pysmt/substituter.py
- pysmt/test/test_formula.py
- pysmt/test/test_oracles.py
- pysmt/test/test_regressions.py
- pysmt/test/test_solving.py
- pysmt/test/test_walkers.py
Refactoring of FNode.get_dependencies() to use iterative walkers.
- Introduces the FreeVarsOracle, and the get_free_variables function/shortcut.
- Added Deprecation warning to get_dependencies
- Updated code-base to use get_free_variables
> Get free Variables

- pysmt/smtlib/parser.py
- pysmt/smtlib/solver.py
- pysmt/test/smtlib/test_generic_wrapper.py
- shippable.sh
- shippable.yml
We were not executing the tests on the solvers wrapper. We now do so on msat.
The configuration is called msat_wrap, and copies mathsat within the test/smtlib/bin directory.
This PR fixes also some issues that appeared after enabling the tests.
> Enabling tests for solvers wrapper

- shippable.yml
This also allows failure of the test, until we update to the new release of mathsat.
> CI: Fix version of Mathsat used in msat_wrap

- pysmt/test/__init__.py
- pysmt/test/test_cnf.py
- pysmt/test/test_euf.py
- pysmt/test/test_int.py
- pysmt/test/test_lira.py
- pysmt/test/test_msat_back.py
- pysmt/test/test_qe.py
- pysmt/test/test_rand.py
- pysmt/test/test_regressions.py
- pysmt/test/test_solving.py
Added methods assertSat, assertUnsat and assertValid to pysmt.TestCase. Applied to most situations in which we were writing self.assertTrue(is_*)
> Adding custom methods to pysmt.TestCase

- pysmt/exceptions.py
- pysmt/solvers/msat.py
- pysmt/solvers/qelim.py
- pysmt/solvers/z3.py
- pysmt/test/test_regressions.py
This PR implements error rising in Z3 quantifier eliminator when a formula containing an unsupported operator is found. This solves #47.
> Z3 lia qe error

- pysmt/solvers/yices.py
- pysmt/test/test_solving.py
This PR adds a more principled support for model extraction in the yices wrapper.
In particular:
* We extract rationals as pairs of integers (numerator / denominator) instead of using doubles.
* For each term that is evaluated, we check if its value is representable within the integer limits, otherwise an error is generated
> Yices int/real number precision

- pysmt/fnode.py
- pysmt/formula.py
- pysmt/test/test_formula.py
- pysmt/utils.py
Added support for the follwing infix operators:
* ```x & y```
* ```x | y```
* ```~x```
* ```-x```
* ```int(x)```
* ```float(x)```
* ```long(x)```
And added support for automatic propotion of python constants to pysmt constants:
E.g.
```python
1.5 + Symbol(x, Real) <= 8
```
> FNODE: Extended support to infix notation as per #92.

- appveyor.yml
- appveyor/install.ps1
- appveyor/run_with_env.cmd
- dev-requirements.txt
- pysmt/test/test_configuration.py
Added support for running tests on Appveyor. This provides some basic CI for windows.
NOTE: Only the library tests are running. No solver is currently being used.
This also creates a directory ci/ in the root of the project, where to store all auxiliary material for running CI, e.g., shippable.sh has been moved there.
> CI: Appveyor support

- shippable.yml
This creates a pkg for each run of the contents of the ./shippable directory, that can be later downloaded.  For now it includes only the code-coverage and xunit data.
NOTE: In the future, this should be used:
- to build the binaries of the solvers to upload to the binary mirror (if not available)
- to build the python package (with a dedicated job)
> CI: Enable artifact creation on shippable

- pysmt/fnode.py
- pysmt/formula.py
- pysmt/test/test_regressions.py
- pysmt/walkers/identitydag.py
Changed FNode's hash to be deterministic among succesive executions and on different machines. This is done by adding an id to each FNode
that is unique within the Formula Manager it belongs to.
This addresses issue #113.
> Changed FNode's hash to be deterministic among succesive executions

- pysmt/smtlib/annotations.py
- pysmt/test/smtlib/test_annotations.py
For a annotation object 'a' it is now possible to write a[f] to obtain all annotations of f.
```
a.annotations(f) == a[f]
```
> SMT-LIB: Added __getitem__ method in Annotations class

- pysmt/environment.py
- pysmt/oracles.py
- pysmt/rewritings.py
- pysmt/shortcuts.py
- pysmt/simplifier.py
- pysmt/smtlib/parser.py
- pysmt/smtlib/printers.py
- pysmt/solvers/eager.py
- pysmt/substituter.py
- pysmt/test/__init__.py
- pysmt/test/examples.py
- pysmt/test/test_eager_model.py
- pysmt/test/test_env.py
- pysmt/walkers/generic.py
The global environment is now inside environment.py module.
The shortcuts get_env and reset_env are still available in shortcuts.py, instead push_env and pop_env are only left in environment.py . The proper way to get the environment from within pysmt is to use pysmt.environment.get_env. Outside of pysmt, we can simply use the shortcut.
> ENVIRONMENT: Relocated the global environment

- pysmt/operators.py
- pysmt/test/test_dwf.py
This is related to the introduction of custom node types.
> operators.all_types(): Return an iterator over all operator types.

- pysmt/printers.py
- pysmt/test/test_printing.py
Smart Printing is meant to provide a way of printing complex expressions using aliases.
Two typical use cases are non-primitive operators and DEFINEs (SMV-style).
For the first case, I provide an example in test_printing.py : `ExactlyOne(x1, ..., xn)` is translated into a disjunction and a set of mutual exclusion constraints. Using smart printing, we can print it as `ExactlyOne(x1, ..., xn)`. 
For now the integration with the rest of the system is weak. You need to manually create the 'smarties' (i.e., the map formula -> string) and call smart_serialize. I think we could:
- Integrate this in FNode.serialize() : If no smarties are provided, SmartPrinter falls-back to the HRPrinter
- Generate the smarties when building expressions, and have a global dictionary of smarties.
> Smart Printing

- pysmt/factory.py
- pysmt/smtlib/solver.py
- pysmt/test/smtlib/test_generic_wrapper.py
Extended constructor of SmtLibSolver, to include information on the
supported logics. This was causing most of the test on generic wrapper
to be skept.
This commit makes sure that BV are tested on the Generic Wrapper.
> Generic Wrapper: Fixed Testing of examples

- pysmt/cmd/shell.py
- Import BV32 and BVType by default
- Enable infix notation in interactive mode
- Provide example of get_model usage in welcome message
> SHELL: Minor extension

- pysmt/environment.py
The Environment can now be extended in a cleaner way, by creating a subclass and deriving the class attributes that define the global services (FormulaManager, TypeChecker, etc.).
This makes it easier for external libraries to extend the handling of new node types, without modifying pySMT (e.g., for theories or logics that are currently not supported by pySMT).
> Improved Environment extensibility

- pysmt/factory.py
- pysmt/test/test_solving.py
Previously, all is_*, qelim, interpolation etc. methods where assuming a ```DEFAULT``` logic, if one was not provided.  All those methods can auto-detect the logic, since the problem is provided in input. Therefore, the new default behavior becomes using ```AUTO_LOGIC```.
> AUTO_LOGIC becomes the new default in methods of Factory.

- pysmt/simplifier.py
Not sure what was the semantics of this line, but it was incorrect.
This was catched by python3.4 on macosx, not on linux... weird...
> BUGFIX: Fix syntax error in Simplifier.walk_plus

- pysmt/exceptions.py
- pysmt/factory.py
- pysmt/solvers/bdd.py
- pysmt/solvers/btor.py
- pysmt/solvers/cvc4.py
- pysmt/solvers/msat.py
- pysmt/solvers/pico.py
- pysmt/solvers/yices.py
- pysmt/solvers/z3.py
Using the ```ImportError``` exception was masking other problems in the solver wrapper. These made debugging harder, since errors were masked by simply saying that the solver was not available.
To address this, the exception ```SolverAPINotFound``` is introduced.
> Better handling of Solver API discovery.

- pysmt/formula.py
- pysmt/test/test_formula.py
- pysmt/test/test_printing.py
- pysmt/typing.py
- FunctionType with 0-arity is equivalent to the return type of the function
- Function application on a 0-arity function returns the symbol
> Fixed issue #188

- pysmt/environment.py
- pysmt/substituter.py
- pysmt/test/test_walkers.py
Made Substituter a super-class for:
- MGSubstituter (Most General)
- MSSubstituter (Most Specific)
This makes it possible to restore the previous behavior, by changing which one is instantiated by the environment.
**Note**: we only allow one global substituter, in order to ensure a consistent behavior. One could argue that an option to the ```substitute()``` function would be cleaner/nicer.
**This is a transitional commit** The default is still the old one (MSS), but a warning has been added in the substitute method.
> Issue 152: Most General substitution

- docs/CHANGES.rst
- examples/README.rst
- examples/smtlib.py
- pysmt/smtlib/annotations.py
- pysmt/smtlib/parser.py
- pysmt/smtlib/script.py
- pysmt/test/smtlib/test_parser_examples.py
- pysmt/test/smtlib/test_parser_extensibility.py
- pysmt/test/test_regressions.py
This example covers the use of the SMT-LIB parsing functions in pySMT.
In particular, we discuss:
- Read a file in SMT-LIB format
- Write a file in SMT-LIB format
- Manipulation of the SMT-LIB script object
- Annotations
- Parser extension with custom commands
This PR fixes also a bug in the parsing of parameters within define-fun.
> Examples: SMT-LIB Parser

- pysmt/smtlib/solver.py
- pysmt/solvers/bdd.py
- pysmt/solvers/btor.py
- pysmt/solvers/cvc4.py
- pysmt/solvers/interpolation.py
- pysmt/solvers/msat.py
- pysmt/solvers/pico.py
- pysmt/solvers/qelim.py
- pysmt/solvers/solver.py
- pysmt/solvers/yices.py
- pysmt/solvers/z3.py
- Exiting from context was not closing the solver, and there was some
confusion on when the resources were actually being closed (i.e., the 
role of __del__)
- This commit removes the need of implementing __del__ in the solvers,
and clarifies the semantics of Solver.exit().
- Solvers need to implement the internal method _exit(), closing open
resources etc.
- The method Solver.exit() can be executed on a closed
solver (following the API of files in Python).
Solvers.exit() takes care of guaranteeing the unique execution.
- Interpolator and QuantifierEliminator have been extended in a
similar way, by introducing an exit() method.
Thanks to **Alberto Griggio** for pointing out this problem.
> Fixed handling of Context, exit() and __del__ within Solver.

- pysmt/solvers/yices.py
- pysmt/test/test_regressions.py
Yices does not support a push after a check_sat call that returned
UNSAT. I added a wrapping logic to handle this case that can arise in
practical applications.
> YICES BUGFIX Fixed a failed assertion in Yices push method

- pysmt/factory.py
- pysmt/logics.py
- pysmt/test/test_solving.py
Top level functions from Factory (and thus most shortcuts) can now
take a logic as a string. Instead of writing
is_sat(f, logic=pysmt.logics.QF_LRA)
it is now possible to write:
is_sat(f, logic="QF_LRA")
This is handled in Factory._get_solver_class(). Other code within
pySMT should always work under the assumption that logics are given as
a pysmt.logics object.
> Issue #220: Logic as String

- pysmt/solvers/eager.py
- pysmt/test/test_eager_model.py
This makes it possible to operate solver-specific models in a more uniform way.
In this way, we can keep using EagerModels, even if solvers provide their own Model Object.
> EagerModel can now take a solver model in input.

- pysmt/logics.py
- pysmt/smtlib/script.py
- pysmt/test/smtlib/test_parser_examples.py
- pysmt/test/test_regressions.py
The logic to be specified in the script was hardcoded as UFLIRA. Now, it is selected by analyzing the formula using the logic oracle.
> BUGFIX: fixed logic dumping in SmtLib

- pysmt/smtlib/commands.py
- pysmt/smtlib/parser.py
- pysmt/smtlib/script.py
- pysmt/test/smtlib/test_smtlibscript.py
- Default parser now deals with SMT-LIB 2.5
- SmtLib20Parser can be used for strict SMT-LIB 2.0 compliance
- Improved handling of not implemented commands in parser
- Test and documentation
Some commands are still not supported by the parser.
> SMT-LIB: Improved parsing compliance wrt SMT-LIB 2 and 2.5

- examples/allsat.py
- pysmt/cmd/install.py
- pysmt/solvers/msat.py
This extends the patch by @agriggio (PR #208) that introduces the new MathSAT5Model object.
We introduce the class ```MSatEnv``` that is used to manage the msat_environment object. In this way, it is possible to decouple the Solver from the Environment, and let the ```MathSAT5Model``` keep an internal reference to the ```MSatEnv``` that survives after the Solver has been closed.
This changes the way that mathsat api functions are called!
> MathSAT Solver: exploiting the new API function msat_get_model()

- pysmt/oracles.py
- pysmt/solvers/bdd.py
- pysmt/solvers/btor.py
- pysmt/solvers/cvc4.py
- pysmt/solvers/yices.py
- pysmt/solvers/z3.py
Removed all annotations disabling linting of star-args that is now not a warning anymore in the new version of pylint
> Removed pylint star-args annotations

- pysmt/cmd/install.py
- pysmt/cmd/installers/btor.py
This also changes the BTOR installer interface to include the version of lingeling in the pkg name.
> Boolector: Updated to version 2.2.0

- pysmt/fnode.py
- pysmt/test/test_formula.py
- pysmt/walkers/dag.py
1. Avoid use of len() to test emptiness of a dictionary
(DagWalker._get_key) and a list (DagWalker._process_stack)
This leads to 75% less calls to len() and a 10% runtime improvement.
2. Use __slots__ for FNode. This leads to 30% memory reduction.
> Basic performance optimizations

- pysmt/logics.py
- pysmt/test/test_logics.py
Linearity information was being incorrectly compared and propagated in logics oracles.
> Fixed bug in Non-linear theories comparison

- pysmt/factory.py
- pysmt/shortcuts.py
- pysmt/smtlib/solver.py
- pysmt/solvers/bdd.py
- pysmt/solvers/btor.py
- pysmt/solvers/cvc4.py
- pysmt/solvers/msat.py
- pysmt/solvers/pico.py
- pysmt/solvers/solver.py
- pysmt/solvers/yices.py
- pysmt/solvers/z3.py
- pysmt/test/smtlib/parser_utils.py
- pysmt/test/test_bdd.py
- pysmt/test/test_regressions.py
- pysmt/test/test_solving.py
!!! Breaking change !!!
Options are now free keyword arguments in the Solver() constructor.
- The parameter ```user_options``` has been removed
- The function ```get_default_options``` has been removed
- The class SolverOptions is used to validate these options. The rest of option handling has been simplified accordingly.
Calls to Factory methods now set meaningful defaults:
- Calls to Factory.is_* are setting the options for model generation and incrementality to False
- Calls to Factory.get_model are done enabling model generation, but disabling incrementality
- Factory.Solver, returns a solver with both model generation and incrementality enabled
> Improved handling of options in Solvers.

- examples/infix_notation.py
- pysmt/decorators.py
- pysmt/shortcuts.py
- pysmt/solvers/solver.py
- pysmt/type_checker.py
Infix notation is automatically enabled when importing shortcuts.py. Internal modules from pysmt should not import shortcuts, and thus still need to explicitely enable infix notation. However, from the user point of view, it becomes more immediate to use it.
There are still some dependencies with the global Type-checker, that we might want to address (however, they are sound).
Updated the example on infix notation accordingly.
> Issue 228: Enable Infix Notation with shortcuts.py

- pysmt/solvers/btor.py
- pysmt/test/test_regressions.py
BTOR requires that LHS of shifts has width that is pow(2).
> BugFix: BTOR handling of bitwidth in shifts

- pysmt/simplifier.py
Extracting expressions from models often returns expressions with many
occurrences of (x <-> {True, False}). This case was not handled by the
simplifier, making the expressions less readable.
> Simplifier:  (a <-> False) into !a

- pysmt/solvers/z3.py
The code was broken: `enumerate(args[1::2])` returns `(0, args[1]), (1, args[3]), ...`, and not
`(1, args[1]), (3, args[3]), ...` as the code was expecting
> fixed bug in Z3Converter.walk_array_value

- pysmt/cmd/install.py
- pysmt/cmd/installers/bdd.py
- pysmt/cmd/installers/btor.py
- pysmt/cmd/installers/cvc4.py
- pysmt/cmd/installers/msat.py
- pysmt/cmd/installers/pico.py
- pysmt/cmd/installers/yices.py
- pysmt/cmd/installers/z3.py
- pysmt/factory.py
- install.py --check  now takes into account the bindings_dir and prints the version of the installed solver
- There is a distinction btw installed solvers and solvers in the python's path.
- Qelim, Unsat-Core and Interpolants are also visualized (but not checked)
See issue #277
> install.py: Improved installed solvers analysis

- .travis.yml
- pysmt/cmd/install.py
- pysmt/cmd/installers/base.py
- pysmt/cmd/installers/msat.py
- pysmt/test/test_bdd.py
- pysmt/test/test_eager_model.py
- pysmt/test/test_formula.py
- pysmt/test/test_regressions.py
- pysmt/test/test_simplify.py
- pysmt/test/test_solving.py
This PR completes the support for python 3.5. With this, we support two versions of python: 2.7 and 3.5. All solvers have been extended/adjusted in order to work with python 3.5.
> Python 3.5

- .travis.yml
This is needed to support both gmpy2 and dReal, since they both depend on libraries that are not available on Ubuntu 12.04, and we do not want to install them manually.
> CI: Upgrade to Trusty

- pysmt/cmd/installers/base.py
This avoids some problems when upgrading C-extensions.
> install.py: Avoid calling is_installed() after installation

- pysmt/fnode.py
- pysmt/test/test_formula.py
All methods in FNode that access the payload now check that the FNode
instance is of the correct type, e.g.:
FNode.symbol_name() checks that FNode.is_symbol()
This prevents from accessing the payload in a spurious way. Since this
has an impact on every access to the payload, it has been implemented as
an assertion, and can be disabled by running the interpreter with -O.
> Assertions protecting FNodeContent.payload access

- pysmt/simplifier.py
- pysmt/test/test_regressions.py
Situations in which two constants were multiplied leading to a 1 value (e.g. ```Times(2, 0.5)```) were being simplified incorrectly.
> BUGFIX: Fix Times simplification when constants evaluate to one

- pysmt/cmd/install.py
- pysmt/cmd/installers/pico.py
Picosat installer only checks pip availability when trying to install it. On systems that do not have pip, it is still possible to use install.py to check if Picosat is available.
> Installers: Make dependency from pip optional

- pysmt/smtlib/script.py
- pysmt/test/test_regressions.py
Serialization of the define-fun expression was using the HR String
representation, instead of calling the SmtLibPrinter.
This had two problems:
1. The expression was not valid SMT-Lib
2. The expression was being thresholded
I inspected the other cases, and this seems to be the only one in which
we were printing an expression.
> BUGFIX: SMT-LIB define-fun serialization

- docs/development.rst
- pysmt/factory.py
Setting the system environment variable ```PYSMT_SOLVERS``` defines which solvers are actually available within pySMT.
This simplifies testing on a single machine, by allowing to mimick the behavior of the CI. Moreover, this is the first step in the refactoring of the CI tests.
> PYSMT_SOLVERS controls available solvers

- pysmt/oracles.py
- pysmt/test/test_size.py
Measure the Boolean size of the formula. This is equivalent to replacing
every theory expression with a fresh boolean variable, and measuring the
DAG size of the formula.
This can be used to estimate the Boolean complexity of the SMT formula.
> SizeOracle: Add MEASURE_BOOL_DAG measure

- pysmt/solvers/z3.py
- pysmt/test/test_back.py
- pysmt/test/test_regressions.py
- pysmt/test/test_solving.py
* Extend Z3 back conversion to allow the introduction of new symbols. 
* Fixed a bug in the back conversion of Times
Both behaviors are possible only if using Tactics from Z3. However, this is something we want to allow in the future, and therefore it is important to have it working now.
> Z3 back conversion

- pysmt/test/examples.py
- pysmt/test/test_bdd.py
- pysmt/test/test_cnf.py
- pysmt/test/test_oracles.py
- pysmt/test/test_printing.py
* Example has a new field 'hr', to store the HR serialization of the
formula;
* Introduced a simplified SExample namedtuple for backwards
compatibility;
* Three methods can be used to iterate over the examples:
* get_example_formula : Returns all SExamples
* get_str_example_formula: Returns all String, Expr and Logic
* get_full_example_formula: Returns all Examples
> Extend Example to include serialized formula

- pysmt/solvers/msat.py
- pysmt/test/test_unsat_cores.py
If the solver was not configured for unsat core, a call to get_unsat_core would lead to an infinite recursion between get_unsat_core and get_named_unsat_core.
This is fixed by checking the configuration of the solver as first thing in those functions.
> MSat: Check if solver is configured for unsat-core

- pysmt/fnode.py
There was a bug when printing the values of Arrays.
```python
a = Array(INT, Int(0), {Int(1):Int(2)})
print a 
```
prints `Array{Int, Int}(0)[1 := 1]` instead of `Array{Int, Int}(0)[1 := 2]`
> fixed a bug when printing arrays

- pysmt/factory.py
- pysmt/fnode.py
- pysmt/printers.py
- pysmt/simplifier.py
- pysmt/smtlib/printers.py
- pysmt/solvers/msat.py
- pysmt/solvers/z3.py
- pysmt/test/examples.py
- pysmt/test/test_printing.py
- pysmt/test/test_regressions.py
- pysmt/test/test_solving.py
- pysmt/walkers/identitydag.py
This PR is the extension of #340.
There is a bug in  ```FNode.array_value_assigned_values_map``` that returns the wromg map of initial values for an array. This PR fixes it.
Thanks to @daniel-rs for noticing the problem
> Fix array values map bug

- .coveragerc
- .travis.yml
- README.rst
- ci/travis_install.sh
- ci/travis_script.sh
Run coverage analysis using coveralls.io .
This is enabled only on master (both PR and push) and for the 'all' configuration, only. This is because enabling coverage tracking slows down the tests quite a bit.
> Coverage via Coveralls

- pysmt/cmd/install.py
- pysmt/cmd/installers/cvc4.py
- pysmt/configuration.py
- pysmt/simplifier.py
- pysmt/smtlib/script.py
- pysmt/smtlib/solver.py
- pysmt/solvers/bdd.py
- pysmt/solvers/btor.py
- pysmt/solvers/cvc4.py
- pysmt/solvers/msat.py
- pysmt/solvers/pico.py
- pysmt/solvers/smtlib.py
- pysmt/solvers/solver.py
- pysmt/solvers/yices.py
- pysmt/solvers/z3.py
- pysmt/test/smtlib/test_generic_wrapper.py
- pysmt/test/test_bdd.py
- pysmt/test/test_rewritings.py
- pysmt/test/test_solving.py
Options that are shared by multiple solvers are handled as keywords
arguments, but solver-dependent options are defined in the
solver_options dictionary:
Solver(name='picosat', generate_models=True,
solver_options={'propagation_limit': 100})
The goal is to clearly separate these two type of configurations.
The use of dictionary for solver_options, makes it simple to store
multiple configurations:
Solver(name=sname, solver_options=myoptions[sname])
All solvers have been ported to this new strategy, by using a custom
SolverOptions object that is responsible for the definition, checking
and setting of the options. This object is used (for example) to
correctly setup the mathsat context.
Option "random_seed" is now supported by all the solvers (that do
support it).
Backwards Incompatible …
> Use solver_options to specify solver-dependent options

- pysmt/solvers/msat.py
> msat solver: get the error message generated by MathSAT when raising a SolverReturnedUnknownResultError

- pysmt/solvers/cvc4.py
- pysmt/solvers/msat.py
- pysmt/test/examples.py
- pysmt/test/test_bv.py
Increased the coverage of BV back_conversion in MathSAT by adding many more BV examples. Additionally, we now have explicit tests for division by BV0. This highlighted some discrepancies in CVC4, that are now properly handled.
> Uniform division by BV0

- pysmt/fnode.py
Re-implemented ```array_value_get``` with a more efficient (and hopefully correct) binary-search.
In this way we avoid the cost of traversing all the children of the ArrayValue node just to get a value.
> More efficient array_value_get

- .coveragerc
- pysmt/__init__.py
- pysmt/test/smtlib/test_smtlibscript.py
- pysmt/test/test_constants.py
- pysmt/test/test_cvc4_quantifiers.py
- pysmt/test/test_int.py
- pysmt/test/test_interpolation.py
- pysmt/test/test_regressions.py
- pysmt/test/test_walkers.py
- pysmt/utils.py
- pysmt/walkers/__init__.py
This PR improves coverage of the test suites by mostly adding new tests.
In detail:
* Disable coverage counting for lines containing "NotImplementedError" (e.g., abstract methods)
* Add tests for constants.py
* Simplify tests for CVC4 Quantifiers
* Fixed wrong test in test_int.py
* Increase coverage for interpolator.py
* Removed unused functions in pysmt.utils
* Increase coverage for walkers.generic.Walker
* Increase coverage for SmtLibIgnoreMixin
> Improve coverage

- pysmt/solvers/cvc4.py
- pysmt/solvers/msat.py
- pysmt/solvers/pico.py
- pysmt/solvers/solver.py
- pysmt/solvers/yices.py
- pysmt/solvers/z3.py
This removes declare_variable from the Solver Interface.
Only BDDs actually use this method to define the static ordering. All
other solvers implementations have been changed to raise a
NotImplementedError.
> Remove Solver.declare_variable

- .coveragerc
- pysmt/test/examples.py
- pysmt/test/test_back.py
- pysmt/test/test_typechecker.py
- pysmt/test/test_walkers.py
- pysmt/type_checker.py
Correct some dead-code in the tests that were discovered by coverage.
Now that the tests have been checked, we omit test/ from the coverage analysis.
> CI: Tests clean-up and disable coverage

- pysmt/solvers/solver.py
- pysmt/test/test_shannon_expansion.py
- pysmt/test/test_solving.py
Non incremental is_sat modifies the stack of assertions. For this
reason, it should be possible to call it only once.
This achieves this by raising an error in solve() if called after a call
to is_sat.
This also clarifies the documentation of Solver.get_model.
Thanks to @colinmorris for the feedback on Solver interface.
> Enforce a single call to is_sat if not incremental

- pysmt/smtlib/parser.py
- pysmt/test/smtlib/test_annotations.py
The parsing of SMTLib2 annotations was incorrect because it interpreted annotation values as expressions. This PR resolves this issue by properly reading the annotation values as uninterpreted strings.
This PR fixes #370
> Fixed annotations parsing according to SMTLib rules 

- pysmt/solvers/solver.py
This was not implemented by any solver. The proper way to set options is during initialization.
> Removed Solver.set_options

- pysmt/cmd/installers/cvc4.py
- pysmt/solvers/cvc4.py
The python bindings name clashes with the modules names both in
solvers and installers. This can create problems in python 2 on some
systems.
We address this by requiring the use of absolute import. Note that we
already do the same for z3.
Thanks to Alexey Ignatiev (@2sev) for bringing this issue to our attention.
> CVC4: Force absolute import of CVC4

- pysmt/solvers/msat.py
Refactor the walk_back in order to replace big `if...elif` with a map. This relies on the possibility of using the TAG for a msat_decl, and use that directly to select the function to perform back conversion. This is now similar to what we do for Z3. 
At the same time, we use the TAGs to perform the same sort of refactoring for the function _get_signature.
> MSat: Back conversion using TAGs

- pysmt/factory.py
- pysmt/shortcuts.py
- pysmt/solvers/btor.py
- pysmt/solvers/eager.py
- pysmt/solvers/msat.py
- pysmt/solvers/options.py
- pysmt/solvers/portfolio.py
- pysmt/solvers/solver.py
- pysmt/test/test_models.py
- pysmt/test/test_portfolio.py
- pysmt/test/test_solving.py
- Created Portfolio class that uses multiprocessing to solve the problem
using multiple solvers.
- The solver provides a naive incremental interface by using
IncrementalTrackingSolver Interface
- get_value and get_model work after a SAT query. Other
artifacts (unsat-core, interpolants) are not supported.
- Extend Factory.is_\* to include `portfolio` key-word, and exported as
is_\* shortcuts. The syntax becomes:
```
is_sat(f, portfolio=["s1", "s2"])
```
Exceptions are currently not handled internally. Similarly, logic testing is done only when the solvers are started (i.e., during solve()).  If at least one solver terminates, this might not be a problem, but it is not nice.
> Portfolio Solver

- appveyor.yml
- pysmt/cmd/install.py
- pysmt/cmd/installers/base.py
- pysmt/cmd/installers/z3.py
This PR does:  
- fix default `smt_solvers` directory in order to be properly handled also on Win  
- fix the message for the option `--env` for Win
- fix `installers\z3.py` in order to install z3 python bindings on Win.
Check done on my win 10 - 64 bit machine:
- calling `install.py  --check`, z3 solver is 'True'
- run `nose .` and the result is 'OK'
> Fix pysmt for z3 solver on windows

- pysmt/cmd/installers/pico.py
Moved PyPi-related picosat installer code in the download function to avoid the need for internet connection on --check and --env commands
This PR addresses issue #384
> Picosat installer with no download in constructor

- README.rst
- pysmt/factory.py
- pysmt/solvers/msat.py
- pysmt/solvers/z3.py
- pysmt/test/test_qe.py
- pysmt/test/test_regressions.py
* Added LIA support in MathSAT Quantifier Eliminator using "LW" algorithm (see issue #387)
* Updated tests for QE
* Changed preference list for QE to prefer LW over FM when using MathSAT
> Adding LIA support to MSat-Based Quantifier Elimination

- pysmt/solvers/btor.py
As suggested by @marcogario, creating a PR (even though "a bit" late) to fix the issue in btor's assumption handling.
> Fixed assumption handling in the Boolector wrapper.

- pysmt/fnode.py
- pysmt/shortcuts.py
- pysmt/smtlib/printers.py
- pysmt/smtlib/script.py
- pysmt/test/test_printing.py
- pysmt/test/test_regressions.py
This PR addresses issues #396 and #397.
I introduced a shortcut ```smtlib_serialize``` and a method of FNode with the same name that return a string representation of the given formula. The ```daggify``` parameter is used to enable or disable the use of ```let``` operators to represent the formulae linearly.
> Print SmtLib term as string shortcut and default to dag SmtLib representation

- pysmt/fnode.py
- pysmt/oracles.py
- pysmt/test/test_imports.py
- pysmt/typing.py
This PR addresses issue #405 .
I created a test that invokes the python interpreter and checks that each pysmt module (except the testing ones and the solvers) can be imported as a standalone (i.e. without previously importing something else).
In order for this test to work I had to move some imports of the environment module inside some functions, but I think this trade-off is acceptable.
> Fixed cyclic import errors

- examples/ltl.py
- pysmt/fnode.py
- pysmt/formula.py
- pysmt/operators.py
- pysmt/oracles.py
- pysmt/printers.py
- pysmt/rewritings.py
- pysmt/simplifier.py
- pysmt/smtlib/printers.py
- pysmt/substituter.py
- pysmt/test/test_dwf.py
- pysmt/test/test_oracles.py
- pysmt/test/test_walker_ext.py
- pysmt/test/test_walkers.py
- pysmt/type_checker.py
- pysmt/walkers/__init__.py
- pysmt/walkers/dag.py
- pysmt/walkers/generic.py
- pysmt/walkers/identitydag.py
*\* This is outdated: See discussion below **
Recover the behavior of the super Walker when inheriting, and easily
compose it.
self.save_super_functions()
must be called during `__init__` **before** overriding the
functions (with set_function). Inside any walk, it is then possible to
call self._super() to execute the original walk, e.g.:
self._super(formula, args, **kwargs)
in case of a DagWalker.
Examples usage using both a DagWalker (BddSimplifier) and
TreeWalker (SmartPrinter) are given.
> Walker Refactoring

- pysmt/simplifier.py
- pysmt/test/test_simplify.py
This PR changes the simplification rules for conjunction and disjunction operators.
The simplification now does three things
- Flattens the And of Ands and the Or of Ors: And(x, And(y, z)) -> And(x, y, z)
- Recognizes the conjunction of x and Not(x) yielding False and the disjunction of x and Not(x) yielding True
- Transforms the argument in a set, thus removing the duplicates: And(x, x, y) -> And(x, y)
> Improved simplification effectiveness on conjunctions and disjunctions

- ci/travis_install.sh
- pysmt/smtlib/script.py
In #397 we made the serialization of an SmtCommand daggified by default. This did not include the methods that operate directly on the SmtLibScript. This commit fixes this left-over.
Fixes #416 .
> Default SMT-LIB Script to daggified serialization

- ci/travis_install.sh
- pysmt/solvers/cvc4.py
The SWIG wrapper is not handling properly the ownership of either SmtEngine or ExprManager, resulting in a memory leak: When the python objects are release the underlying C++ are not destroyed.
This commit works-around the issue by forcing the ownership of the SmtEngine to the python wrapper. When the wrapper is destroyed, the C++ is also destroyed.
A proper patch for CVC4 should be designed in order to properly account also for the release of the ExprManager, and the fact that ExprManager is ref'd within SmtEngine (but SWIG has no way of knowing this).
See http://www.swig.org/Doc1.3/Python.html#Python_nn30 for an explanation of the memory management features in SWIG.
> CVC4: Free C++ SmtEngine when Solver is destroyed

- pysmt/solvers/z3.py
walk_ methods for Z3Converter are created when the Z3Converter class
is defined via the make_walk_nary and make_walk_binary
> Z3Converter: Remove use of deprecated self.functions

- pysmt/oracles.py
- pysmt/test/test_oracles.py
The TypesOracle was not able to correctly determined the types of expressions with constants, since constants were ignored.
> TypesOracle: Fix handling of constants

- pysmt/solvers/z3.py
- pysmt/test/test_regressions.py
The current implementation did not consider the possibility of converting a formula having an ITE as a top-level operator.
> Fixed z3 converter to support ITE terms at top-level.

- pysmt/cmd/check_version.py
- pysmt/cmd/installers/base.py
- pysmt/cmd/installers/bdd.py
- pysmt/cmd/installers/btor.py
- pysmt/cmd/installers/cvc4.py
- pysmt/cmd/installers/msat.py
- pysmt/cmd/installers/pico.py
- pysmt/cmd/installers/yices.py
- pysmt/cmd/installers/z3.py
Separated and simplified from PR #407. 
Main changes:
- Renamed check_module_version.py into check_version.py; fixed its internal structure and changed return value from "ERROR" to "NOT INSTALLED". If there is an error, the script will exit with a non-zero status, and we can print this information for debugging
- Fixed installation for cvc4, btor and picosat. Since we are not using os.system anymore, we need to perform each command separately and we cannot rely on the shell patterns.
- Removed some left-overs functions from previous attempts
> Installers: Simpler version check via subprocess

- appveyor.yml
- pysmt/cmd/install.py
- pysmt/cmd/installers/base.py
- pysmt/cmd/installers/z3.py
- pysmt/constants.py
- pysmt/solvers/z3.py
- pysmt/test/test_nlira.py
This PR brings the pysmt Z3 version to 4.5.0, addressing issue #393.
Unfortunately, right now the tests fail (and Z3 cannot be updated) due to the following Z3 issue  https://github.com/Z3Prover/z3/issues/1005.
> Z3: Upgrade to 4.5.1 (dev)

- pysmt/fnode.py
- pysmt/formula.py
- pysmt/shortcuts.py
- pysmt/test/test_formula.py
When using infix notation, it would be nice to write ```x != y```. However, this is not possible for the same reasons that we do not allow ``` x == y```. The current way to write this in infix notation would be: ```~ x.Equals(y)```, that is not particularly readable in my opinion. 
This introduces a new function in fnode so that we can write ```x.NotEquals(y)```.
> Infix: Add NotEquals

- pysmt/smtlib/parser/parser.py
- pysmt/test/test_regressions.py
SMT-LIB parsing of bv constants using the hexadecimal syntax
(e.g., #x10) would leads to the incorrect width of the bit-vector.
Fixes issue #442. Thanks to @cdmcdonell for reporting this.
> Bugfix: SMTLIB Parsing #x BV constants

- pysmt/formula.py
- pysmt/solvers/btor.py
- pysmt/test/__init__.py
- pysmt/test/test_bv.py
- pysmt/test/test_constants.py
Automatically convert GMPY object in the BV constructor.
Previously, BV(mpz(5), 8) would create a node with a mpz object in the
payload *independently* of whether GMPY was enabled or not.
The behavior of the BV constructor is now consistent with the behavior of
Int and Real.
Tests for this have been added in test_constants.py. See Issue #435 .
> BV: Convert GMPY object in BV constructor

- examples/einstein.py
Revised Einstein examples in order to use weaker Implies everywhere (as pointed out by @frmsaul).
Rewrote expressions to make better use of infix notation and gaining in readability.
> Examples: Revised Einstein example

- pysmt/test/test_sorts.py
- pysmt/typing.py
Constructors for ArrayType and FunctionType take other sorts. Due to the
similar spelling of constant constructor and types, it is easy to type:
ArrayType(Real, Real)
instead of
ArrayType(REAL, REAL)
This change adds a check in those constructors to enforce the arguments
to be of type PySMTType.
> Sorts: Stronger type checks for composite sorts

- pysmt/test/test_formula.py
- pysmt/test/test_regressions.py
- pysmt/test/test_typechecker.py
- pysmt/type_checker.py
`LT` and `LE` are only allowed over (INT, INT) and (REAL, REAL), while equals is allowed for ('a, 'a) except if `a is BOOL.
The previous behavior allowed `Equals(BOOL, BOOL)` and also `LT(BV[8], BV[8])`
> Fixed type-checking of Equals, LT and LE.

- examples/model_checking.py
The MC example was not implementing correctly: the simple path condition imposed a constraint over the entire assignments instead of each state of the system, and the indexing for unrolling and k hypothesis were out of 1
> Fixed indexing and simple path condition in MC example

- pysmt/solvers/z3.py
This branche fixes @bellert issue reported on #328. 
It seems that `Z3Exception`s are no longer derived from `z3.Z3Exception` but also from `z3.z3types.Z3Exception`.
> Fixinf Z3 exception handling

- pysmt/cmd/shell.py
To append `dict_keys` to `list`, need to explicitly convert them.
> Fix pysmt CLI for Python3 (closes #492)

- pysmt/cmd/install.py
- pysmt/cmd/installers/msat.py
- pysmt/cmd/installers/z3.py
Modify `z3` and `msat` installers in order to make their shared binary objects (libraries/dlls) auto-discoverable, without the need for setting `LD_LIBRARY_PATH`/`PATH`.
Tested on Linux, but not on Windows.
> Simplify shared lib usage

- pysmt/shortcuts.py
> shortcuts enables warnings only within pySMT package

- pysmt/shortcuts.py
BVAShr is a shift operator. I guess this is a copy&paste error from the BVRor below?
> Fix docstring for BVAShr.

- pysmt/fnode.py
- pysmt/test/test_bv.py
- pysmt/test/test_formula.py
FNode.bv_str provides multiple formats for printing bv constants: binary (b), decimal (d), and hexadecimal (x).
Unsigned operators used to have only the infix notation with operators (eg., bv1 & bv2), creating an asymmetry between infix operators that are expressible with the textual notation and not.
All BV operators now have the textual infix notation (eg., bv1.BVAnd(bv2)). In addtion, unsigned operators maintain the usual infix notation.
> FNode.bv_str: Multiple format for BV printing

- pysmt/cmd/installers/msat.py
Before this commit, I get the following message:
```
$ pysmt-install --msat
...
ld: warning: directory not found for option '-L$ORIGIN'
```
From my brief perusing of the internet, it seems that `$ORIGIN` is a linux specific construct.
> [msat-installer] Don't use $ORIGIN on darwin

- .travis.yml
- README.rst
- appveyor.yml
- ci/travis_install.sh
- ci/travis_script.sh
- docs/getting_started.rst
- pysmt/cmd/install.py
- pysmt/cmd/installers/base.py
Removes need for `PYTHONPATH` patching.
Bulk of work in 7d496ce, the remaining commits update docs and tests.
Addresses #495.
> Install solvers to a relevant site-package by default

- examples/generic_smtlib.py
- pysmt/smtlib/solver.py
- pysmt/test/smtlib/test_generic_wrapper.py
The current generic smtlib solver seems to not support variables with custom types (a.k.g. sorts).
This PR fixes the issue by sending a `(declare-sort)` command to the generic solver, whenever declaring a variable whose sort was not previously declared.
The `generic_smtlib.py` was edited in order to accommodate this change.
> SMTLIB: Supporting custom sorts in generic solvers

- pysmt/solvers/z3.py
The Z3Solver was deleting the reference to the z3.Solver without deleting the reference to the Converter. Since the converter internally used the ctx from the solver, this might cause the issues from #522 and #465.
> Z3: Fixed deallocation sequence in Solver

- pysmt/solvers/z3.py
Address #522 by explicitly checking if the context is still available on ``Z3Converter.__del__``
> Z3: Check context presence on del

- pysmt/simplifier.py
- pysmt/test/test_bv_simplification.py
This pull request implements the simplification of bit vector items in some trivial cases, such as simplifying BVAdd(x, BVZero(n)) to BVZero(n). Therefore, users may not need to call the expensive BDD simplifier for those trivial cases.
> Trivial improvements for bit vector simplification

- .travis.yml
- ci/travis_before_install.sh
- ci/travis_install.sh
Upgrade CI to use python 3.7 . 
The CI environment uses an older version of SWIG (2.X), but CVC4 requires SWIG 3. We install SWIG 3.0.10 from source.
See https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905
> CI: Python 3.7 on Linux

- pysmt/cmd/install.py
- pysmt/cmd/installers/z3.py
- pysmt/factory.py
- pysmt/solvers/z3.py
- pysmt/test/test_interpolation.py
- pysmt/test/test_nlira.py
This PR updates Z3 to version 4.8.4.
Notes:
* Array models are forced to be represented using the uncompressed style in pysmt, see https://github.com/Z3Prover/z3/issues/1769 for details
* This PR removes the interpolation via Z3 because the authors of Z3 decided to drop it: https://github.com/Z3Prover/z3/pull/1646
> Ported Z3 to version 4.8.4

- pysmt/smtlib/parser/parser.py
- pysmt/test/smtlib/test_parser_examples.py
Collection.deque does not have a method pop that takes arguments (i.e. `pop(0)` does not exist). I replaced the method with `popleft()` which achieve the same result as the intended one.
> Fix bug in deque pop in smtlib/parser

- pysmt/walkers/generic.py
Importing `Iterable` from `collections` is deprecated in python3.7 and will be removed in python3.8
https://docs.python.org/3/library/collections.html
> Fix import warning in python 3.7

- ci/travis_before_install.sh
It appears that yices and picosat need swig, because the master branch was failing travis on my fork: https://travis-ci.org/makaimann/pysmt/builds/507901966
This just installs swig for those two solvers as well.
> Install swig for yices and picosat in Travis build

- pysmt/simplifier.py
- pysmt/test/test_simplify.py
the args of the times args are processed using a stack. Each call
to simplify reverts the order of nonlinear multiplication. And because of that
the simplify function could not reach a fix-point if called repeatedly.
As a solution, we perform sorting of the arguments while doing simplication.
> sort the times args while simplifying

- azure-pipelines.yml
- pysmt/__init__.py
This PR introduces 2 changes:
1. The azure pipeline is extended to include uploading to PyPI test server after the build succeeds on master
2. A new way of automatically computing version numbers for dev version.
I would leave this targeting pypi-test for a while, until we are confident that it works as expected.
Notice that the credentials for the pypi test server are stored in azure. See https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops
> Upload to PypPi (Test)

- pysmt/__main__.py
- pysmt/cmd/install.py
- setup.py
Two commands are defined as main function of pysmt
```python -m pysmt install``` 
and 
```python -m pysmt shell```
This removes the bin alias for pysmt-shell, but preserves pysmt-install.
> Define main function for pysmt as module

- make_distrib.sh
- pysmt/__init__.py
- pysmt/cmd/install.py
- pysmt/test/test_regressions.py
When running a dev version, we use git to compute the version number. This works ok if we are running pysmt from the git checkout.
However, if we do pip install of a dev version, this can fail. This PR provides a default value for this.
This is more of a temporary fix and a principled solution would be appreciated.
> Static Version number in package

- pysmt/solvers/btor.py
This is a very simple fix for btor to correctly support the `IncrementalTrackingSolver` interface. Currently, getting the assertions from a `BoolectorSolver` always gives a list of `None`, because `_add_assertion` doesn't return anything.
This change just returns `formula` from _add_assertion for tracking in self._assertion_stack.
> Fix assertion tracking for boolector

- pysmt/solvers/btor.py
EDIT: Actually, it turns out that the latest version of boolector does not have this restriction any more. Thus, the best solution is to simply call the relevant boolector shift method without any rewriting (implemented here: https://github.com/pysmt/pysmt/pull/592/commits/39b2c8e3c8d062ed3cd991dd22cffbf4a4eb5a6f). Thanks to @mpreiner for pointing this out.
Through the API, boolector requires that the second argument to a shift has a width that is `log2` of the first argument's width. This is handled in PySMT by extracting the lower bits of the second argument. However, there can be a problem here for bit-vectors of width 1.
Example:
Running the following:
```
x = Symbol('x', BVType(1))
y = Symbol('y', BVType(1))
res = Symbol('res', BVType(1))
s = Solver(name='btor') …
```
> Handle one-bit shifts in btor

- pysmt/solvers/msat.py
Fixes an issue in the mathsat signature for concat. This was causing issues for `sequence_interpolant` when the interpolant contained `concat` because the signature wouldn't match.
> Fix mathsat signature for BV_CONCAT

- pysmt/formula.py
- pysmt/shortcuts.py
- pysmt/test/smtlib/test_parser_examples.py
For the time-being I kept the binary internal representation of `BVConcat`, but we might consider to switch to a n-ary representation as for `Plus`.
> Fixed #620 by allowing n-ary BVConcat in the frontend 

- pysmt/solvers/yices.py
- pysmt/test/test_regressions.py
The problem was a bad control in the conversion of BV constants: the yicespy swig API uses 64-bit signed longs, so the maximum number convertible via that API is 2^63-1. I fixed the control that falls back to string-based conversion.
> Fixed issue #596

- pysmt/test/test_simplify.py
- run_all_tests.sh
- run_tests.sh
There was a problem with multiprocessing and nose. The issue seems to be the global environment being affected in some tests and not properly isolated by nose.
This PR simply disables (and updates to python3) the `run_tests.sh` script.
> Fix Issue 633

- pysmt/environment.py
- pysmt/fnode.py
- pysmt/formula.py
- pysmt/oracles.py
- pysmt/simplifier.py
- pysmt/solvers/solver.py
- pysmt/test/test_nlira.py
- pysmt/test/test_oracles.py
- pysmt/test/test_solving.py
* Check if we are trying to create an expression `Div(x, Real(0))`, if so, raise a User warning, if the configuration flag `enable_div_by_0`.
* Check for div by 0 in simplifier
* Extend TheoryOracle to return a non-linear theory for expressions with division by 
---
*Old Proposal*
When creating a Div expression, we check whether the right hand side is a 0. If so, we replace the entire expression with a new variable. In this way, we preserve the SMTLIB semantics of Div, while keeping the model extraction and other operations simple.
Since getting a result due to a division by zero is always surprising, we add a user warning when performing the translation and make it possible to disable it with the configuration variable `Environment.replace_div_by_0`
See discussion in …
> Support for division by Zero

- pysmt/cmd/installers/btor.py
The install script for Boolector sets `-DPYTHON_LIBRARY` by reading
`sysconfig.get_config_var('LIBDIR')`, which returns the directory that
holds the Python library. This variable gets read by Boolector's build
system when calling `find_package(PythonLibs ...)`. The problem is that
CMake's `FindPythonLibs` doesn't expect a directory but rather the full
path to Python's library [0]. This results in warnings such as:
```
WARNING: Target "pyboolector" requests linking to directory "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib".  Targets may link only to libraries.  CMake is dropping the item.
```
and makes the build fail on macOS. When linking `pyboolector.so` the
linker fails due to missing references to symbols such as
`_PyBaseObject_Type`.
Additionally, setting …
> Fix Boolector install script

- pysmt/logics.py
The keyword argument `integer_arithmetic=True` was missing
from the constructor of `pysmt.logics.Logic` for the logic
UFNIA [1, 2] ("Non-linear integer arithmetic with uninterpreted
sort and function symbols." [1]). See for example how the
logic QF_UFNIA is defined in the same module.
A consequence of the previous definition of UFNIA was
type checking errors due to numerals without `'.'` being
parsed as reals instead of integers in the module
`pysmt.smtlib.parser.parser` [3].
[1] http://smtlib.cs.uiowa.edu/logics.shtml
[2] http://smtlib.cs.uiowa.edu/logics-all.shtml#UFNIA
[3] https://github.com/pysmt/pysmt/blob/35ac3fd88b01706ba01d2a7cf291194fda0c8f92/pysmt/smtlib/parser/parser.py#L665-L672
> BUG: define UFNIA as logic with integer arithmetic

- .github/workflows/cla.yml
- .mailmap
- CONTRIBUTING
- CONTRIBUTORS
- ci/cla.sh
- docs/development.rst
- pysmt/__init__.py
We require all contributors to submit a change to CONTRIBUTORS as a way to confirming acceptance of the CLA.
To check this, we compare the git log with the entries in the CONTRIBUTORS file.
Since users might have sent commits with different names/emails, we introduce a `.mailmap` to provide canonical names.
The CONTRIBUTORS data has been updated with the content of CLAHub.
We seem to be missing a few:
Require CLA:
* Caleb Donovick b0f031d9f595dddbd4febd3dd3bad487f3e112d9
* en.magnago 2b9a879ac9fbe9253d05655b3212dd0a13a37273
Typos in documentation (might consider whitelisting these changes)
* Guillem Francès 6562e2662496291a5578facecb140d7f41f8ab4d
* Matthew Fernandez 39e6d252239d63472b2a28a901bd0bcce42237dd
>  CLA: Add utility to check for CLA

- pysmt/factory.py
- pysmt/oracles.py
- pysmt/shortcuts.py
- pysmt/simplifier.py
- pysmt/solvers/msat.py
- pysmt/solvers/z3.py
- pysmt/test/test_rewritings.py
- pysmt/test/test_simplify.py
- pysmt/walkers/identitydag.py
I found an issue in which the simplify procedure crashed because it could not handle an algebraic constant.
In my case the expression to be simplified was an addition.
The code `res = sum(x.constant_value() for x in args)` was returning a res of type z3.Numeral, which the later call to `self.manager.Real(res)` could not handle.
I copy pasted the structure used in walk_times for walk_plus, and tried to handle the algebraic constant also in the walk for the pow and minus operators.
I added the `walk_algebraic_constant` method to the identity walker.
This happened while using z3 as SMT solver.
The converter in z3.py was not able to handle node of type algebraic constant, I tried to implement it. I am not sure whether this is the correct or best way to implement it. In my use cases it seems …
> Handling of algebraic constants in simplify

- pysmt/formula.py
- pysmt/simplifier.py
- pysmt/solvers/msat.py
- pysmt/test/test_nia.py
This should improve the support for integer division.
In formula.py:
* I have removed an unnecessary exception that was raised if the rhs of a division was an integer constant.
* The warning "division by 0" is raised also in the case of integer division.
In simplifier.py:
* I think the simplification was buggy in python3 since the `/` operator performs division between rationals.
* In addition the standard C-like integer division is not consistent with the smtlib2 semantics.
As far as I understand the semantics of division between integers of smtlib2 is as follows:
`n / d` is `floor(float(n) / d)` if `d > 0` and `ceil(float(n) / d)` if `d < 0`.
http://smtlib.cs.uiowa.edu/theories-Ints.shtml
In msat.py:
* an integer division is rewritten in terms of `floor` and `divide` operations, where …
> Integer div

- CONTRIBUTORS
- pysmt/cmd/installers/cvc4.py
Fix of installation script for CVC4 to use `PYTHON_EXECUTABLE` as done in #656. 
In addition, use `multiprocessing.cpu_count()` to get the number of parallel `make` jobs.
> Fix CVC4 installation on macOS

- pysmt/rewritings.py
- pysmt/test/test_rewritings.py
I found a simple bug in times distributor.   
These commits should fix the issue and add a simple test case. 
The current implementation of TimesDistributor rewrites the inequality `(x - (x + y)) < 0` into `(x + (-1 * x)) < 0`.
> Bug in times distributor

- pysmt/solvers/solver.py
- pysmt/test/test_solving.py
I often end up writing something like:
```
for constr in iterable:
solver.add_assertion(constr)
```
so I thought having a method in solver to add all constraints from an iterable could be useful.    
This does not do anything clever like trying to optimise the addition of multiple constraints.
Another possibility could be to replicate what is done in the FormulaManager for methods such as `And` and `Or`, hence having a single method accepting both a single instance and an iterable.
> implement add_assertions method for solver.

- CONTRIBUTORS
- pysmt/smtlib/solver.py
- pysmt/test/smtlib/test_generic_wrapper.py
This fixes the problem raised in this issue #674. "get_model" of generic solver fails because it call "get_value" for all variables in the environment, this may cause an error as some variables do not appear in the formula.
An error is raised when the parser fails to extract the value of a variable (doesn't appear in the formula) from the response of the generic solver.
> Fix "get_model" when called from a generic solver (Fix #674)

- CONTRIBUTORS
- pysmt/solvers/portfolio.py
- pysmt/test/test_portfolio.py
Thank you for this project!
I encountered an issue while using `Portfolio` where the solvers weren't respecting the passed `logic`. I found that they were using the default logic ([`QF_UFLIRA`](https://github.com/pysmt/pysmt/blob/22520e2a012c980285fae10fe8aa388e263ea317/pysmt/factory.py#L47)), and these changes were required in order to start each solver with the correct logic, as passed to `Portfolio`.
> Fix to correctly pass logic to solvers started by Portfolio

- azure-pipelines.yml
- ci/install_unix.sh
This PR fixes a problem with the CI using old images of ubuntu that are now deprecated in Azure Pipelines.
Using the `-latest` images we should be able to remain up-to-date with new OS images
> Updated docker images to solve deprecation issue on azure pipelines

- .mailmap
- pysmt/formula.py
- pysmt/shortcuts.py
- pysmt/test/test_formula.py
This pull request adds the possibility to use several BV operators as left-associative, affected operators are BVAnd, BVOr, BVAdd, and BVMul.
The nodes themselves still only have two children, the formula manager was updated to allow passing an arbitrary number of operators after the left and right operator. The generated formula is created in a left-associative manner as indicated in https://smtlib.cs.uiowa.edu/theories-FixedSizeBitVectors.shtml.
This also allows pySMT to read SMT-LIB scripts using these BV operators with more than two children.
A test was added in pysmt/test/test_formula.py demonstrating the new behavior.
> Add possibility to use several BV operators as left associative

- MANIFEST.in
Fix for https://github.com/pysmt/pysmt/issues/608. The config was missing from the MANIFEST file and thus not being included.
> Fix missing file in Manifest

- pysmt/cmd/install.py
This is pre-work for https://github.com/pysmt/pysmt/pull/719. 
Since the changes to 5.6.7 are failing the CI for osx, I wanted to make sure there was no issue up to 5.6.6 (from 5.6.1).
> Upgrade MathSAT to 5.6.6

- .github/workflows/test.yml
Refine the CI triggers to only run tests for pushes on `master` or PRs targeting `master`.
> CI: Avoid running on PR branch push

- pysmt/cmd/install.py
- pysmt/cmd/installers/msat.py
Update MathSAT to 5.6.7. This includes changes on how the OSX version is package to be architecture independent (thus support the M1 architecture).
See https://github.com/pysmt/pysmt/issues/709
> Upgrade MathSAT to 5.6.7

- pysmt/formula.py
Closes #696 
FormulaContextualizer is singleton in FormulaManager.
Instantiated the first time `normalize` is called.
> make FormulaContextualizer singleton in FormulaManager.

- CONTRIBUTORS
- examples/sudoku/sudoku.py
The pull request fixes the print statements to support python3 and concatenation of a list to a `dict_keys` object [here](https://github.com/akumm2k/pysmt/blob/a1214157332a06404e506feb1c16bf5e3ba274f8/examples/sudoku/sudoku.py#L159).
> Make sudoku.py Python3 compatible

- .mailmap
- CONTRIBUTORS
- pysmt/formula.py
Also, I tried this quick-and-dirty differential testing script and it looks good to me:)
```python
import subprocess
from pysmt.shortcuts import simplify, BV
WIDTH = 5  # Do not set to a multiple of 4
for i in range(2**WIDTH):
a = BV(i, WIDTH)
for j in range(i):
b = BV(j, WIDTH)
pysmt_output = simplify(a.BVXnor(b)).to_smtlib()
z3_input = f'(simplify (bvxnor {a.to_smtlib()} {b.to_smtlib()}))'
cmd = f'echo "{z3_input}" | z3 -in'
z3_output = subprocess.check_output(cmd, shell=True).decode('utf-8').strip()
if pysmt_output != z3_output:
raise RuntimeError(f'expected {z3_output}, got {pysmt_output}')
```
> Fix the definition of BVXnor

- pysmt/logics.py
- pysmt/test/test_logics.py
In https://github.com/pysmt/pysmt/issues/731#issuecomment-1200380943, we discussed how having a non-deterministic answer in `get_logic` can lead to problems.
We do not expect the logic detection in `get_logic` to pick "the best" logic, but we want at least to fail consistently so that users are aware that a logic needs to be specified.
This PR does two things:
1. Adds QF_LIRA to the set of `PYSMT_LOGICS`, this was the trigger for the work, but only adding this logic does not solve the problem.
2. Adds a test for showing that `get_closer_logic` is deterministic independently of the the order of the input argument `supported_logics`.
**Alternatives Considered**
There was another way to fix the same that would have been to make both `PYSMT_LOGICS` and `SMTLIB_LOGICS` an ordered set. I …
> Deterministic get_closer_logic

- pysmt/smtlib/parser/__init__.py
Pick the fix for `pyximport` from https://github.com/pysmt/pysmt/pull/761 so CI can be green in master
> Fix for pyximport

- CONTRIBUTORS
- pysmt/solvers/btor.py
- pysmt/test/examples.py
- pysmt/test/test_array.py
- pysmt/test/test_solving.py
The conversion of "const array" terms was not yet implemented for Boolector.
This PR implements the conversion of pysmt array types into btor array sorts:
https://github.com/pysmt/pysmt/blob/743ff01f994b57437db6251866dbc39074f494de/pysmt/solvers/btor.py#L532-L534
and add support for building `ConstArray` instances with associated array stores (inpired from both msat and z3 converters):
https://github.com/pysmt/pysmt/blob/743ff01f994b57437db6251866dbc39074f494de/pysmt/solvers/btor.py#L513-L521
It also removes the `test_btor_does_not_support_const_arrays` and replace it with a test to ensure nothing breaks when building a const array with Boolector:
https://github.com/pysmt/pysmt/blob/743ff01f994b57437db6251866dbc39074f494de/pysmt/test/test_array.py#L79-L83
> [Boolector] Add support for const arrays and boolean indices/elements

- docs/CHANGES.rst
- pysmt/__init__.py
Relaese branch for 0.9.6. This used the release notes generated by GH to speed up things. In order to do so, we create a draft release using the release branch and auto-generate the release notes.
We than copy the notes to the changelog and commit the file.
We then change the target for the relase to be master again.
Note: I put the 24th as release date.
**Next steps:**
> Release 0.9.6

- pysmt/smtlib/printers.py
- pysmt/test/test_printing.py
When printing a real constant in SMTLib, we used a notation `(/ n d)` where `n` is the integer numerator  and `d` the integer denominator. 
This causes issues on more restrictive parsers, so we now print `(/ n.0 d.0)` to force a rational interpretation.
> Fixed issue #778

- pysmt/formula.py
- pysmt/smtlib/parser/parser.py
- pysmt/test/smtlib/test_smtlibscript.py
- pysmt/test/test_regressions.py
- pysmt/test/test_typechecker.py
Fixes: https://github.com/pysmt/pysmt/issues/784
This fixes the issue by type-checking every newly created node even when it is found in the `formulae` map.
No overhead should have been added as the type is cached.
This also fixes the tests where a type error in smtlib was not noticed, and adds new ones.
Minor: This also fixes the decision on retrying building a type-invalid node in the smtlib parser. Namely, if there are no integer constants within the arguments, there is nothing to change and an exception is directly raised.
> Fix Create node does not raise type error

- pysmt/parsing.py
- pysmt/test/test_hr_parsing.py
Fix bug in HRParser, where identifiers having names starting with a keyword where incorrectly parsed
Note:  the parser is still incomplete, as it cannot parse identifiers having the name of a keyword e.g. "Int > 10"
> HRParser: bug in identifiers names

- CONTRIBUTORS
- pysmt/shortcuts.py
- pysmt/test/test_formula.py
I added `Abs` as a shortcut for Ite(x > 0, x, -x). 
I haven't yet added support for parsing the `abs` SMT-LIB function and simplifying it into Ite(x > 0, x, -x). Let me know if you think this would be a useful addition.
- [ x ] For bugs or new features, make sure there is a test showing the bug or demonstrating the use of the new feature
- [ x ] Are all tests green?
- [ x ] (First contribution only) You accepted the licensing terms by adding name and email to the CONTRIBUTORS file (see https://github.com/pysmt/pysmt/blob/master/docs/development.rst#licensing).
> Added Abs shortcut as shorthand for Ite(x > 0, x, -x)

- .mailmap
- CONTRIBUTORS
- pysmt/rewritings.py
- pysmt/test/test_cnf.py
This PR fixes the `CNFizer` `walk_function` method, renaming `function_symbol` (deprecated name) with `function_name`
fixes #801
> Fix issue 801

- pysmt/substituter.py
- pysmt/test/test_formula.py
The test reported in issue #767 highlighted an issue in the substituter which was unable to correctly handle the case of a function application.
The base case for the `walk_function` is implemented in the `Substituter` class, but this function does not handle substitutions, only interpretations, hence I forced the code to pass through the `MGSubstituter` or the `MSSubstituter` before calling the `Substituter.walk_function`.
I believe this should be the correct path.
> Fixed issue #767
